### ISSUE TITLE
Partial use of Express Belt

### ISSUE THREAD

**Issue by minyan** [Ben-Ramchandani/OutpostPlanner#1]
I click the GUI, and change it to Express belt (and Medium pole), but the GUI selection is keeping the yellow belt, and adding express belt.  

The blueprint that being generated using both belt.  
I wish it only using one belt.

Edit : also happen in splitter usage (it used both)

**Comment by Martinii89** [comment]
I didn't see it documented anywhere, but you can drop a yellow belt in the GUI to make it "forget" the yellow belt. It seems like the default behavior calculates the resources generated per second for each row, and only uses the more expensive belts where needed.

**Comment by Ben-Ramchandani** [comment]
M4rtini89 is correct, click with a transport belt to remove it from the list.

I've updated the in-game text and the readme, so hopefully it's clearer now.
