### ISSUE TITLE
 Doesn't seem to be compatible with the mod, Max Rate Calculator.

### ISSUE THREAD

**Issue by ArcaniVictus** [Ben-Ramchandani/OutpostPlanner#13]
Attempting to change the rate option in Max Rate Calculator crashes my game to the main menu and gives the following error:
"Error while running event OutpostPlanner::on_gui_click (ID 1)
OutpostPlanner/gui.lua:270: attempt to index local 'frame' (a nil value)"

Screenshot:
https://i.imgur.com/R5IZcJK.jpg

My game also crashes to main menu just attempting to open the Outpost planner GUI. It gives a different error for this crash:

Error while running event OutpostPlanner::on_gui_click (ID 1)
OutpostPlanner/gui.lua:461: attempt to index field 'OutpostBuilderWindow' (a nil value)

The issues are resolved if I remove the mod, Max Rate Calculator.  However, I would very much like to be able to use them both if you have the time to work out the issue.

I would also like to let you know how amazing this mod is! I have been wanting something like this for a very long time as I hate setting up mining outpost even with regular blueprints. I finally broke (after 1k hours) and starting searching the other day and came across your mod. I've loved it ever since! This works exactly as I had hoped it would when it comes to quickly building mining excavators over fields of ore.

Thanks again!

**Comment by Ben-Ramchandani** [comment]
Should be fixed by 1.0.4, see https://mods.factorio.com/mod/OutpostPlanner/discussion/5bf5b99b3ea6e6000d812575 for discussion :)
