### ISSUE TITLE
Compatibility with factorio 0.17

### ISSUE THREAD

**Issue by glouel** [Ben-Ramchandani/OutpostPlanner#14]
Sorry to bother you but I wanted to ask if you planned to look into supporting version .17 of factorio. OutpostPlanner truly is an excellent and useful mod, so if anything, you have my thanks for all the work that you previously put on it.

**Comment by Ben-Ramchandani** [comment]
Thank you for the kind words!

I have just finished updating the mod, I'm going to upload it to the mod portal now :)

It looks like it's all working with just a few minor changes, but I'm going to be pretty busy for a couple of weeks now so if something is badly broken I might not be able to fix it for a while - use at your own risk!

**Comment by glouel** [comment]
This is awesome, thank you so much for taking the time to update it. I'll report back if I see anything but don't worry too much about it if so ;)
