### ISSUE TITLE
Bot based outpost

### ISSUE THREAD

**Issue by Martinii89** [Ben-Ramchandani/OutpostPlanner#3]
Would it be possible to make it skip belts and place provider chests between the miners to support a bot based mining outpost?

**Comment by Ben-Ramchandani** [comment]
This is now supported in 0.1.7, click on the transport belt button while holding a chest. I'm going to leave this issue open for now until I find a better way to integrate it with the GUI.

Thanks for the suggestion, hope you're finding the mod useful.

Edit: I'm currently rewriting the mod to support custom blueprints (including chests), so I'm going to leave the current GUI as is and close this issue.
