### ISSUE TITLE
Belt make a turn before clearing the mining drill

### ISSUE THREAD

**Issue by minyan** [Ben-Ramchandani/OutpostPlanner#5]
As usual, a pic is explained more than my words.
![untitled](https://user-images.githubusercontent.com/829593/27858210-944b7fda-619e-11e7-8ddf-3e1c01996ce5.jpg)
I'm not sure whether this issue is exist in other orientation, but the one i notice is orienting West.

**Comment by Ben-Ramchandani** [comment]
Thank you again, this should be fixed in 0.1.8. It was the same bug as last time just in a different direction :P

**Comment by minyan** [comment]
Thanks for the update
