### ISSUE TITLE
Module Support

### ISSUE THREAD

**Issue by lukas-gerster** [Ben-Ramchandani/OutpostPlanner#6]
Is it possible to request modules for the miners? I like production modules to stretch my supply.

**Comment by Ben-Ramchandani** [comment]
I'm going to try and add support for custom blueprints to the mod, but I'm afraid it will take a few days at least.

**Comment by Ben-Ramchandani** [comment]
The latest release (0.3.0) supports modules.

Open the Advanced menu, click on the Default example button with an empty blueprint and add modules to the miners in the blueprint before clicking on the Read Blueprint button.
