### ISSUE TITLE
Set Factorio version to 0.15 in info.json

### ISSUE THREAD

**Issue by ja-ko** [Ben-Ramchandani/OutpostPlanner#8]
In info.json you have factorio_version set to 0.15.0 which even though factorio parses this just fine is imho syntactically incorrect. It should be 0.15 instead, since 0.15 covers the whole 0.15 range while 0.15.0 covers just a single version of factorio. 

I noticed this problem because [this tool](https://github.com/mickael9/fac) refuses to update the mod because it claims the factorio_version of the mod is too old compared to my 0.15.34 server.

It'd be awesome if you could fix it. Thanks for creating the mod!

**Comment by Ben-Ramchandani** [comment]
Thanks for the info, that makes sense.

I've fixed it in version 0.3.2.
