### ISSUE TITLE
[Feature Request] Button in basic options to swap out the miner used

### ISSUE THREAD

**Issue by Lezreth** [Ben-Ramchandani/OutpostPlanner#9]
This mod is great!  However it is a minor hassle to go into the blueprint to change the miner used by the planner.  I would like to see a button added to the basic options to allow the user to swap out the miner to any custom miner that shares the same footprint as the one in the blueprint.

**Comment by Ben-Ramchandani** [comment]
Thanks for the idea, this is included in version 0.5.0. I've moved all the entity buttons to advanced settings (it was getting cluttered).
